
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// AFNetworking
#define COCOAPODS_POD_AVAILABLE_AFNetworking
#define COCOAPODS_VERSION_MAJOR_AFNetworking 2
#define COCOAPODS_VERSION_MINOR_AFNetworking 5
#define COCOAPODS_VERSION_PATCH_AFNetworking 0

// AFNetworking/NSURLConnection
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLConnection
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLConnection 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLConnection 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLConnection 0

// AFNetworking/NSURLSession
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLSession
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLSession 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLSession 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLSession 0

// AFNetworking/Reachability
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Reachability
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Reachability 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Reachability 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Reachability 0

// AFNetworking/Security
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Security
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Security 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Security 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Security 0

// AFNetworking/Serialization
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Serialization
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Serialization 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Serialization 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Serialization 0

// AFNetworking/UIKit
#define COCOAPODS_POD_AVAILABLE_AFNetworking_UIKit
#define COCOAPODS_VERSION_MAJOR_AFNetworking_UIKit 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_UIKit 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_UIKit 0

// BButton
#define COCOAPODS_POD_AVAILABLE_BButton
#define COCOAPODS_VERSION_MAJOR_BButton 4
#define COCOAPODS_VERSION_MINOR_BButton 0
#define COCOAPODS_VERSION_PATCH_BButton 2

// FMDB
#define COCOAPODS_POD_AVAILABLE_FMDB
#define COCOAPODS_VERSION_MAJOR_FMDB 2
#define COCOAPODS_VERSION_MINOR_FMDB 4
#define COCOAPODS_VERSION_PATCH_FMDB 0

// FMDB/common
#define COCOAPODS_POD_AVAILABLE_FMDB_common
#define COCOAPODS_VERSION_MAJOR_FMDB_common 2
#define COCOAPODS_VERSION_MINOR_FMDB_common 4
#define COCOAPODS_VERSION_PATCH_FMDB_common 0

// FMDB/standard
#define COCOAPODS_POD_AVAILABLE_FMDB_standard
#define COCOAPODS_VERSION_MAJOR_FMDB_standard 2
#define COCOAPODS_VERSION_MINOR_FMDB_standard 4
#define COCOAPODS_VERSION_PATCH_FMDB_standard 0

// FrameAccessor
#define COCOAPODS_POD_AVAILABLE_FrameAccessor
#define COCOAPODS_VERSION_MAJOR_FrameAccessor 1
#define COCOAPODS_VERSION_MINOR_FrameAccessor 3
#define COCOAPODS_VERSION_PATCH_FrameAccessor 2

// HKCircularProgressView
#define COCOAPODS_POD_AVAILABLE_HKCircularProgressView
#define COCOAPODS_VERSION_MAJOR_HKCircularProgressView 1
#define COCOAPODS_VERSION_MINOR_HKCircularProgressView 1
#define COCOAPODS_VERSION_PATCH_HKCircularProgressView 0

// MBProgressHUD
#define COCOAPODS_POD_AVAILABLE_MBProgressHUD
#define COCOAPODS_VERSION_MAJOR_MBProgressHUD 0
#define COCOAPODS_VERSION_MINOR_MBProgressHUD 9
#define COCOAPODS_VERSION_PATCH_MBProgressHUD 0

// MKFoundationKit/NSArray
#define COCOAPODS_POD_AVAILABLE_MKFoundationKit_NSArray
#define COCOAPODS_VERSION_MAJOR_MKFoundationKit_NSArray 1
#define COCOAPODS_VERSION_MINOR_MKFoundationKit_NSArray 2
#define COCOAPODS_VERSION_PATCH_MKFoundationKit_NSArray 3

// Masonry
#define COCOAPODS_POD_AVAILABLE_Masonry
#define COCOAPODS_VERSION_MAJOR_Masonry 0
#define COCOAPODS_VERSION_MINOR_Masonry 5
#define COCOAPODS_VERSION_PATCH_Masonry 3

// RESideMenu
#define COCOAPODS_POD_AVAILABLE_RESideMenu
#define COCOAPODS_VERSION_MAJOR_RESideMenu 4
#define COCOAPODS_VERSION_MINOR_RESideMenu 0
#define COCOAPODS_VERSION_PATCH_RESideMenu 7

// ReactiveCocoa
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa 3
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa 1

// ReactiveCocoa/Core
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa_Core
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa_Core 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa_Core 3
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa_Core 1

// ReactiveCocoa/UI
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa_UI
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa_UI 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa_UI 3
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa_UI 1

// ReactiveCocoa/no-arc
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa_no_arc
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa_no_arc 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa_no_arc 3
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa_no_arc 1

